In [29]:
import torch
import numpy as np
print(torch.__version__)

1.0.0


In [2]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninit = torch.Tensor(3,3)
tensor_uninit

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.numel(tensor_uninit)

9

In [6]:
tensor_uninit

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
tensor_int = torch.randn(5,4).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0,  0],
        [ 0,  3,  1,  0],
        [-1,  0,  0,  0],
        [ 0,  0,  0, -2],
        [-1,  0,  0,  0]], dtype=torch.int32)

In [13]:
tensor_long = torch.LongTensor([1.9, 3, 46.3, 369])
tensor_long

tensor([  1,   3,  46, 369])

In [15]:
tensor_ones = torch.ones(100)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
tensor_zeroes = torch.zeros(50)
tensor_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [18]:
tensor_eye = torch.eye(4)
tensor_eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [19]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [24]:
# In-place operation = same tensor
# They have '_' suffix

initial_tensor = torch.rand(3,3)
initial_tensor.fill_(9)
initial_tensor

tensor([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]])

In [25]:
# Out-place operation = generate new tensor

new_tensor = initial_tensor.add(3)
new_tensor

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

In [28]:
initial_tensor.add_(5)

tensor([[14., 14., 14.],
        [14., 14., 14.],
        [14., 14., 14.]])

## Tensor and Numpy share same memory

In [30]:
numpy_arr = np.array([3,6,9])
numpy_arr

array([3, 6, 9])

In [31]:
tensor_numpy = torch.from_numpy(numpy_arr)
tensor_numpy

tensor([3, 6, 9])

In [33]:
numpy_from_tensor = tensor_numpy.numpy()
numpy_from_tensor

array([3, 6, 9])

In [35]:
numpy_arr[1] = 5
numpy_arr

array([3, 5, 9])

In [36]:
tensor_numpy

tensor([3, 5, 9])

In [37]:
tensor = torch.randn(4,3)
tensor

tensor([[ 0.8254, -0.0334, -0.2556],
        [ 0.0609,  1.2324, -1.1303],
        [-1.2510,  1.1917, -2.3108],
        [ 0.6875,  1.5541, -1.7490]])

In [41]:
tensor[0,0]

tensor(0.8254)

In [42]:
# all the elements from all the rows and column from 2nd to last

tensor[:,1:]

tensor([[-0.0334, -0.2556],
        [ 1.2324, -1.1303],
        [ 1.1917, -2.3108],
        [ 1.5541, -1.7490]])

In [43]:
tensor.size()

torch.Size([4, 3])

In [46]:
# resize should be done in such a way that the elements are included
# cannot write 'tensor.view(11)'

resized_tensor = tensor.view(12)
resized_tensor

tensor([ 0.8254, -0.0334, -0.2556,  0.0609,  1.2324, -1.1303, -1.2510,  1.1917,
        -2.3108,  0.6875,  1.5541, -1.7490])

In [47]:
tensor[0,0] = 369
resized_tensor

tensor([ 3.6900e+02, -3.3399e-02, -2.5563e-01,  6.0891e-02,  1.2324e+00,
        -1.1303e+00, -1.2510e+00,  1.1917e+00, -2.3108e+00,  6.8754e-01,
         1.5541e+00, -1.7490e+00])

In [49]:
resized_tensor = tensor.view([6,2])
resized_tensor

tensor([[ 3.6900e+02, -3.3399e-02],
        [-2.5563e-01,  6.0891e-02],
        [ 1.2324e+00, -1.1303e+00],
        [-1.2510e+00,  1.1917e+00],
        [-2.3108e+00,  6.8754e-01],
        [ 1.5541e+00, -1.7490e+00]])

In [50]:
# values are sorted in ascending order row-vice

sorted_tensor, sorted_indices = torch.sort(tensor)
sorted_tensor

tensor([[-2.5563e-01, -3.3399e-02,  3.6900e+02],
        [-1.1303e+00,  6.0891e-02,  1.2324e+00],
        [-2.3108e+00, -1.2510e+00,  1.1917e+00],
        [-1.7490e+00,  6.8754e-01,  1.5541e+00]])

In [51]:
sorted_indices

tensor([[2, 1, 0],
        [2, 0, 1],
        [2, 0, 1],
        [2, 0, 1]])

In [52]:
# use 'dim=0' to sort column-vice

sorted_tensor, sorted_indices = torch.sort(tensor, dim=0)
sorted_tensor

tensor([[-1.2510e+00, -3.3399e-02, -2.3108e+00],
        [ 6.0891e-02,  1.1917e+00, -1.7490e+00],
        [ 6.8754e-01,  1.2324e+00, -1.1303e+00],
        [ 3.6900e+02,  1.5541e+00, -2.5563e-01]])

In [53]:
sorted_indices

tensor([[2, 0, 2],
        [1, 2, 3],
        [3, 1, 1],
        [0, 3, 0]])